### ISSUE TITLE
cebsocket on windows

### ISSUE THREAD

**Issue by yft22** [rohanrhu/cebsocket#1]
Hi,

Compiling the project on linux is OK for me but when I try to compile on windows via msys mingw I get this error:

gcc -c -o _cebsocket.o src/cebsocket.c -std=c99 -I. -I/c/openssl-master/include -g -lssl -lcrypto -lpthread -lm
In file included from src/cebsocket.c:24:
src/../include/cebsocket.h:14:10: fatal error: bits/stdint-uintn.h: No such file or directory
   14 | #include <bits/stdint-uintn.h>

Do you have an idea?

**Comment by rohanrhu** [comment]
Hi @yft22, thank you for feedback! I've fixed it. Also I've made a chat example placed in `examples/chat`.

You can try the latest revision.

**Comment by rohanrhu** [comment]
Ah.. we need an abstraction for Wiinsocks. I will make it soon.

**Comment by yft22** [comment]
thanks @rohanrhu !

Do you think adding something like this will help ?

#ifdef __WIN32__
# include <winsock2.h>
#else
# include <sys/socket.h>
#endif

**Comment by rohanrhu** [comment]
> thanks @rohanrhu !
> 
> Do you think adding something like this will help ?
> 
> #ifdef **WIN32**
> 
> # include <winsock2.h>
> #else
> 
> # include <sys/socket.h>
> #endif

Yes. We need using Winsock.. I'm very busy right now. You can send a PR if  you do it 🙂

**Comment by rohanrhu** [comment]
A very late update but you can use [MSYS2](https://www.msys2.org/) to build things using Cebsocket and ship with MSYS2 DLLs that are used.

Here is a good way to get MSYS2 DLLs: https://github.com/msys2/MINGW-packages/issues/5204#issuecomment-1013818547

Steps you should follow to ship your app built in MSYS2 shell:

* You need to install MSYS2 first and use **MSYS2 shell**. (Not MSYS2/MinGW64 or MSYS2/MinGW32 shells!)

* On MSYS2 shell you should install things like GCC, Make and others...

```bash
pacman -S ntldd gcc make libopenssl openssl-devel
```

*(Maybe I'm missing some packages...)*

* Building is same:

```bash
cd cebsocket/examples/chat
make
mkdir -p win32-build
cp chat.exe win32-build
```

* For shipping your app to Win32 target just do this:
```bash
ldd win32-build/* | grep -iv system32|grep -vi windows|grep -v :$  | cut -f2 -d\> | cut -f1 -d\( | tr \\ / |while read a; do ! [ -e "win32-build/`basename $a`" ] && cp -v "$a" win32-build/; done
```

Your executable should be in `win32-build` folder and this quick command will copy MSYS2 DLLs that your executable needs. You can simply ship your executable and required DLLs together which is placed in `win32-build` folder. `win32-build/chat.exe` doesn't need to run on MSYS2 environment anymore... with MSYS2 DLLs it will work on Windows without any other dependency.

Your `win32-build` folder will have MSYS2 DLLs like this:

    rohan@milkyway MSYS /c/proje/cebsocket/examples/chat/win32-build
    $ ls
    chat.exe  msys-2.0.dll  msys-crypto-1.1.dll  msys-z.dll

    rohan@milkyway MSYS /c/proje/cebsocket/examples/chat
    $ file chat.exe
    chat.exe: PE32+ executable (console) x86-64, for MS Windows

MSYS2 is a great thing! It enables us to build our applications that are using Linux and POSIX APIs.
